### ISSUE TITLE
Импорт ProxyConnector

### ISSUE THREAD

**Issue by Fahreeve** [nibrag/aiosocks#10]
Добавь возможность импортировать не только так: 
```python
from aiosocks.connector import ProxyConnector
```
но и так:
```python
import aiosocks
a = aiosocks.connector.ProxyConnector
```

**Comment by nibrag** [comment]
Для этого нужно в aiosocks.__init__ испортить connector, это приведет:
- кросс импорт
- Если импортить connector в __init__, то в connector запустится импорт aiohttp. Не всем нужен коннектор и в частности http протокол. Из-за этого появится лишняя зависимость для людей, кто не пользуется http протоколом.

Можешь так:
```
import aiosocks.connector
a = aiosocks.connector.ProxyConnector
```

**Comment by Fahreeve** [comment]
Да я так и делаю, но прост у меня код выглядит так:
```python
import aiosocks
import aiosocks.connector
```
думал, может получится одним импортом обойтись. Но если это вызывает такие проблемы в твоем проекте, то лучше пусть все останется как есть)
