### ISSUE TITLE
"limit_per_host" and "enable_cleanup_closed" is not used in aiohttp.TCPConnector anymore

### ISSUE THREAD

**Issue by lifetyper** [nibrag/aiosocks#11]
For the ProxyConnector Class,
the super().__init__()  inside  __init__() function  is still passing args "**limit_per_host**" and "**enable_cleanup_closed**",these args are not used in aiohttp.TCPConnector anymore.

I think these two args should be removed from aiosocks too.

**Comment by nibrag** [comment]
Is used:
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L188
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L171

**Comment by lifetyper** [comment]
I don't quite understand why show me the code of BaseConnector,ProxyConnector is child of TCP Connector,right?

These two args are not used in TCP Connector ,super ()_init_() is the init of TCPConnector,this raised error for unexpected args.

**Comment by lifetyper** [comment]
Infact I'm using aiosocks in my project and met this error when testing,and remove these two args just  fixed the error.

**Comment by nibrag** [comment]
These options are added in the aiohttp 2.0 (https://github.com/aio-libs/aiohttp/blob/2.0/aiohttp/connector.py#L514)
aiosocks 0.2.1+ depends on aiohttp 2.0+
If you need the first version aiohttp, use aiosocks 0.1.7

**Comment by lifetyper** [comment]
All right,my mistake.
