### ISSUE TITLE
aiohttp 3 incompatibility

### ISSUE THREAD

**Issue by Usever** [nibrag/aiosocks#28]
Please, add aiohttp 3.0.0 support.

Thank you.

**Comment by brooks-macbeth-shadowdragon** [comment]
Keep getting the following traceback:

    Traceback (most recent call last):
    ...
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiosocks/connector.py", line 56, in __init__
        enable_cleanup_closed=enable_cleanup_closed)
    TypeError: __init__() got an unexpected keyword argument 'resolve'

Proposed fix: remove the `resolve` keyword.

I would very much like to use this package, but it keeps failing.

**Comment by keepitsimple** [comment]
Any ETA or updates on this issue?

**Comment by romis2012** [comment]
It seems this project is abandoned. If you don`t need aiohttp < 3.0 support try [aiosocksy](https://github.com/romis2012/aiosocksy) package

**Comment by nibrag** [comment]
added in master
