### ISSUE TITLE
cookies not used in session?

### ISSUE THREAD

**Issue by ahxxm** [nibrag/aiosocks#3]
switching from TCPConnector to Socks(5)Connector, I tried: a) session.cookies_jar.update_cookies, b) session.connector.cookies[key] = value

the calls succeeded, but response shows a login page instead.

wondering whether I'm using it improperly or it just ignores cookie...

**Comment by nibrag** [comment]
Which version aiohttp you use?

**Comment by ahxxm** [comment]
i tried 0.20 and 1.0.2

**Comment by nibrag** [comment]
Work for me:
```
addr = aiosocks.Socks5Addr('localhost', 1080)
auth = aiosocks.Socks5Auth('proxyuser2', 'password2')

conn = SocksConnector(proxy=addr, proxy_auth=auth, loop=loop)
with aiohttp.ClientSession(loop=loop, connector=conn) as session:
    session._cookie_jar.update_cookies({'a': 'b'})
    async with session.get(url) as response:
        html = await response.text()
```
You can verify this using a network sniffer.

**Comment by ahxxm** [comment]
which version of aiohttp are you using?
thanks for testing, I'll test more thoroughly later and report

**Comment by nibrag** [comment]
0.22.5

**Comment by ahxxm** [comment]
i checked cookies and found it's a string strip issue of my own..

thank you!
