### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by devblack** [nibrag/aiosocks#41]
**Create a new released of the current version**, because the released #0.2.6 have the error "**ImportError: aiosocks.SocksConnector require aiohttp library**" thank you.

**Comment by SmileyJames** [comment]
@nibrag a release to pip would be hugely appreciated. All this hard work fixing bugs and maintaining the code, but it's not available for use. If you are short on time I would expect we could find people with time to set up some ci to do it regularly.

**Comment by rigens** [comment]
This project is buggy by design and has been abandoned for a long time. Use [aiohttp-socks](https://github.com/romis2012/aiohttp-socks) instead

**Comment by devblack** [comment]
> This project is buggy by design and has been abandoned for a long time. Use [aiohttp-socks](https://github.com/romis2012/aiohttp-socks) instead

Thx
